import { TableData } from './../../models/table-data';
import { DatePipe } from '@angular/common';
import { NumberHeaderComponent } from '../number-header/number-header.component';
import { Headerdata } from './../../models/header-data';
import { Component } from '@angular/core';
import { TableComponent } from "../table/table.component";

@Component({
  selector: 'app-number-parent',
  imports: [NumberHeaderComponent, TableComponent],
  templateUrl: './number-parent.component.html',
  styleUrl: './number-parent.component.scss',
})
export class NumberParentComponent {
  headerData: Headerdata;
  tableData: TableData[] = [];
  constructor() {
    this.headerData = {
      protocolName: 'فودافون مصر',
      country: 'المملكة الأردنية الهاشمية',
      currentClient: 'الشركة الألمانية للإبادة',
      extensionCount: 9,
      lastShipmentDate: new Date('2024-12-29'),
      currentCredits: 5000,
      clientUsedCredits: 5000,
      totalUsedCredits: 5000,
    };
    this.tableData = [
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-01-01'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 10,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-02-01'),
        releaseDate: new Date('2023-11-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 11,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 12,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 13,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 14,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-04-01'),
        releaseDate: new Date('2023-09-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 15,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-05-01'),
        releaseDate: new Date('2023-08-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 16,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-06-01'),
        releaseDate: new Date('2023-07-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 17,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-07-01'),
        releaseDate: new Date('2023-06-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 18,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-08-01'),
        releaseDate: new Date('2023-05-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 19,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-01-01'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 20,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-02-01'),
        releaseDate: new Date('2023-11-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 21,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-03-01'),
        releaseDate: new Date('2024-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 22,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-03-01'),
        releaseDate: new Date('2024-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 23,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-03-01'),
        releaseDate: new Date('2024-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 24,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-04-01'),
        releaseDate: new Date('2023-09-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 25,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-05-01'),
        releaseDate: new Date('2024-08-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 26,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-06-01'),
        releaseDate: new Date('2024-07-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 27,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-07-01'),
        releaseDate: new Date('2024-06-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 28,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-08-01'),
        releaseDate: new Date('2024-05-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 29,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-01-01'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-02-01'),
        releaseDate: new Date('2024-11-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-04-01'),
        releaseDate: new Date('2023-09-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 40,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-05-01'),
        releaseDate: new Date('2023-08-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-06-01'),
        releaseDate: new Date('2023-07-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 60,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-07-01'),
        releaseDate: new Date('2023-06-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-08-01'),
        releaseDate: new Date('2023-05-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-01-01'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 70,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-02-01'),
        releaseDate: new Date('2023-11-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 80,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-04-01'),
        releaseDate: new Date('2023-09-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-05-01'),
        releaseDate: new Date('2023-08-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-06-01'),
        releaseDate: new Date('2023-07-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 80,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-07-01'),
        releaseDate: new Date('2023-06-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-08-01'),
        releaseDate: new Date('2023-05-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-01-01'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-02-01'),
        releaseDate: new Date('2023-11-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 90,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 1,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-04-01'),
        releaseDate: new Date('2023-09-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-05-01'),
        releaseDate: new Date('2023-08-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-06-01'),
        releaseDate: new Date('2023-07-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 2,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-07-01'),
        releaseDate: new Date('2023-06-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-08-01'),
        releaseDate: new Date('2023-05-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-01-01'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-02-01'),
        releaseDate: new Date('2023-11-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-04-01'),
        releaseDate: new Date('2023-09-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-05-01'),
        releaseDate: new Date('2023-08-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-06-01'),
        releaseDate: new Date('2023-07-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-07-01'),
        releaseDate: new Date('2023-06-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-08-01'),
        releaseDate: new Date('2023-05-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-01-01'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2024-02-01'),
        releaseDate: new Date('2023-11-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-03-01'),
        releaseDate: new Date('2023-10-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-04-01'),
        releaseDate: new Date('2023-09-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-05-01'),
        releaseDate: new Date('2023-08-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-06-01'),
        releaseDate: new Date('2023-07-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-07-01'),
        releaseDate: new Date('2023-06-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-08-01'),
        releaseDate: new Date('2023-05-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-04-01'),
        releaseDate: new Date('2023-09-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-05-01'),
        releaseDate: new Date('2023-08-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-06-01'),
        releaseDate: new Date('2023-07-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-07-01'),
        releaseDate: new Date('2023-06-30'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 122,
        cost: 61890,
      },
      {
        client: 'الشركة الالمانية لإبادة الحشرات',
        registrationDate: new Date('2023-08-01'),
        releaseDate: new Date('2023-05-31'),
        registrarName: 'عبدالرحيم إسماعيل ناصف',
        localMinutes: 7654,
        internationalMinutes: 9,
        cost: 61890,
      },
    ];
  }
}
